config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'users#index'
  resources :users, only: %i[index show update] do
    collection do
      get 'test'
      get 'privacy'
    end
  end

  resources :relationships, only: %i[create destroy] do
    member do
      get 'followers'
      get 'following'
    end
  end

  resources :books, only: %i[create destroy] do
    collection do
      get 'search'
    end

    member do
      get 'review', to: 'reviews#show'
      put 'review', to: 'reviews#update'
    end
  end
end

app/views/shared/_header.html.haml
%nav.navbar.navbar-white.py-2.fixed-top
  .container
    %a.navbar-brand.mr-0{ href: "/" }
      = image_tag('header-logo.png',
        alt: 'BOOKLABO',
        class: 'header-logo')
    .form-inline.d-none.d-sm-inline
      = render 'shared/search-form'
    %ul.navbar-nav
      - if user_signed_in?
        %li.nav-item
          = link_to(user_path(current_user),
                    id: 'users-show-link',
                    class: 'nav-link') do
            %i.fas.fa-user-circle.fa-2x
        %li.nav-item.pl-1
          = link_to(destroy_user_session_path,
                    method: :delete,
                    id: 'users-sign-out-link',
                    class: 'nav-link') do
            %i.fas.fa-sign-out-alt.fa-2x
      - else
        %li.nav-item.pl-1
          = link_to(new_user_session_path,
                    class: 'nav-link') do
            %i.fas.fa-sign-in-alt.fa-2x
.search-form.bg-white.d-sm-none.py-4
  .container
    .form-inline.px-4.justify-content-center
      = render 'shared/search-form'

app/views/shared/_pagination.html.haml
.card-footer.bg-white
  %nav#pagination-nav{ data: {page: page, total: total_items} }
    %ul.pagination.justify-content-center.mt-3
      - ((total_items / 20).ceil).times do |i|
        %li.page-item
          = link_to(search_books_path(keyword: keyword,
            page: i),
            data: {page: i},
            class: "page-link page-link-num rounded") do
            = i + 1
    %p.pagination-text
      - unless books.length == 1
        全#{total_items}件中 #{page.to_i * 20 + 1} - #{page.to_i * 20 + @books.length}件を表示
      - else
        全#{total_items}件中 #{page.to_i * 20 + 1}件を表示

app/views/shared/_post-book-modal.haml
.modal.fade#post-book-modal{ aria: { hidden: true },
                             role: "dialog",
                             tabindex: "-1" }
  .modal-dialog.modal-dialog-centered{ role: "document" }
    .modal-content
      .modal-header
        %h5.modal-title 本を登録する
        %button.close{ aria: { label: "Close" },
                       data: { dismiss: "modal" },
                       type: "button" }
          %span{ aria: { hidden: true } }
            %i.fas.fa-times.text-muted
      .modal-body.row
        = image_tag('',
            class: 'modal-book-img col-4',
            id: 'modal-book-img')
        .modal-text.col-8
          %h6#modal-book-title
          %p#modal-book-author
      .modal-footer
        .modal-footer-btn#read-book{ data: { dismiss: 'modal',
                                             toggle: 'modal' },
                                     href: '#post-review-modal' }
          %i.fas.fa-book.pr-2
          読んだ本に登録
        .modal-footer-btn#reading-book{ data: { status: 1 } }
          %i.fas.fa-book-open.pr-1
          %span 読んでる本に登録
        .modal-footer-btn#will-read-book{ data: { status: 2 } }
          %i.fas.fa-sticky-note.pr-1
          %span 読みたい本に登録

app/views/shared/_post-review-modal.haml
.modal.fade#post-review-modal{ aria: { hidden: true },
                               role: "dialog",
                               tabindex: "-1" }
  .modal-dialog.modal-lg.modal-dialog-centered{ role: "document" }
    .modal-content
      .modal-header
        .modal-title.post-review-title 読んだ本に登録する
        %button.close{ aria: { label: "Close"},
                       data: {dismiss: "modal"},
                       type: "button" }
          %span{ aria: { hidden: true } }
            %i.fas.fa-times.text-muted
      .modal-body.row#modal-book-data
        .col-sm-3.border-right.text-center
          = image_tag('',
                      class: 'post-review-img',
                      id: 'post-review-img')
        .modal-text.col-sm-9
          %form{ class: "post-review" }
            .row.mb-2
              %label{ for: "date",
                      class: 'col-lg-3 post-review-label my-auto' }
                読み終わった日
              .input-group.date.col-lg-5#datetimepicker{ data: { target: { input: "nearest" } } }
                %input{ type: 'text',
                        name: 'date',
                        data: { target: '#datetimepicker' },
                        id: 'date-input',
                        class: 'form-control datetimepicker-input review-date' }
                .input-group-append{ data: { target: '#datetimepicker',
                                      toggle: "datetimepicker" } }
                  .input-group-text.border-0#calender
                    %i.fa.fa-calendar
              .col-lg-4.my-auto.post-review-label
                %input.date-check#date-check{ type: "checkbox" }
                読了日を指定しない
            .row.mb-1
              %label{ for: 'text',
                      class: 'col-lg-3 post-review-label' }
                感想・レビュー
              %textarea{ type: 'text',
                         name: 'text',
                         rows: 8,
                         id: 'review-text',
                         class: 'review-text col form-control mx-2' }
            .row.mb-1
              .word-count-text.ml-auto.mr-3
                %span.word-count#word-count<>0
                ／255文字
            .row.mb-2.mx-2
              .col-lg-3
              %input{ type: 'hidden',
                      name: 'rating',
                      value: 0,
                      id: 'book-rating' }
              .book-rating.pr-3.my-auto#review-post-rating
                %i.fas.fa-star.fa-lg#rating-1{ data: { rating: 1 } }
                %i.fas.fa-star.fa-lg#rating-2{ data: { rating: 2 } }
                %i.fas.fa-star.fa-lg#rating-3{ data: { rating: 3 } }
                %i.fas.fa-star.fa-lg#rating-4{ data: { rating: 4 } }
                %i.fas.fa-star.fa-lg#rating-5{ data: { rating: 5 } }
              %span.rating-reset#rating-reset
                評価なし
            .row
              .col-3
              .col-9.d-flex.pl-0
                - if session[:oauth_token].present?
                  %input#tweet-review{ type: 'hidden',
                                       name: 'tweet',
                                       value: false }
                  .tweet-btn#tweet-btn
                    %i.fab.fa-twitter
                %button{ id: 'review-submit',
                         class: 'review-submit ml-auto my-0' }
                  登録する

app/views/shared/_review-form.html.haml
%form.post-review
  .row.mb-2
    %label{ for: "date",
            class: 'col-3 post-review-label my-auto' }
      読み終わった日
    .input-group.date.col-5.pl-0#datetimepicker{ data: { target: { input: "nearest" } } }
      %input{ type: 'text',
              name: 'date',
              data: { target: '#datetimepicker' },
              id: 'date-input',
              class: 'form-control datetimepicker-input review-date' }
      .input-group-append{ data: { target: '#datetimepicker',
                            toggle: "datetimepicker" } }
        .input-group-text.border-0#calender
          %i.fa.fa-calendar
    .col-4.my-auto.post-review-label
      %input.date-check#date-check{ type: "checkbox" }
      読了日を指定しない
  .row.mb-1
    %label{ for: 'text',
            class: 'col-3 post-review-label' }
      感想・レビュー
    %textarea{ type: 'text',
                name: 'text',
                id: 'review-text',
                class: 'review-text col form-control mr-3' }
  .row.mb-1
    .word-count-text.ml-auto.mr-3
      %span.word-count#word-count<>0
      ／255文字
  .row.mb-2
    .col-3
    %input{ type: 'hidden',
            name: 'rating',
            value: 0,
            id: 'book-rating' }
    .book-rating.pl-0.pr-3.my-auto
      %i.fas.fa-star.fa-lg{ data: { rating: 1 } }
      %i.fas.fa-star.fa-lg{ data: { rating: 2 } }
      %i.fas.fa-star.fa-lg{ data: { rating: 3 } }
      %i.fas.fa-star.fa-lg{ data: { rating: 4 } }
      %i.fas.fa-star.fa-lg{ data: { rating: 5 } }
    %span.rating-reset#rating-reset
      評価なし
  .row
    .col-3
    .col-9.d-flex.pl-0
      .tweet-btn.my-o
        %i.fab.fa-twitter
      %button{ id: 'review-submit',
                class: 'review-submit ml-auto my-0' }
        登録する

app/views/shared/_search-form.html.haml
= form_with(url: search_books_path,
  data: {remote: false},
  method: :get) do |f|
  .input-group
    = f.search_field(:keyword,
      placeholder: '本のタイトル・著者名',
      class: 'form-control form-control-sm')
    = hidden_field_tag(:page, 0)
    .input-group-append
      %button.input-group-text.bg-white{ id: 'search-submit',
                                         type: 'submit' }
        %i.fas.fa-search.text-muted

app/views/shared/_show-review-modal.html.haml
.modal.fade#show-review-modal{ aria: { hidden: true },
                               role: "dialog",
                               tabindex: "-1" }
  .modal-dialog.modal-lg.modal-dialog-centered{ role: "document" }
    .modal-content.show-review-modal
      .modal-header
        .modal-title
          %h2.review-book-title#book-title
          %h6.review-book-author#book-authors
        %button.close{ aria: { label: "Close"},
                       data: {dismiss: "modal"},
                       type: "button" }
          %span{ aria: { hidden: true } }
            %i.fas.fa-times.text-muted
      .modal-body.row#modal-book-data
        .col-sm-3.border-right.text-center
          = image_tag('book-default.png',
                      class: 'post-review-img',
                      id: 'book-img')
        .modal-text.col-sm-9
          .row.mb-3
            .col-lg-3.show-review-label
              読み終わった日：
            .col-lg-3.review-show-text#review-show-date
          .row.mb-3
            .col-lg-3.show-review-label
              評価：
            .col-lg-3
              .review-rating#review-show-rating
                %i.fas.fa-star.fa-lg#rating-1
                %i.fas.fa-star.fa-lg#rating-2
                %i.fas.fa-star.fa-lg#rating-3
                %i.fas.fa-star.fa-lg#rating-4
                %i.fas.fa-star.fa-lg#rating-5
          .row.mb-3
            .col-lg-3.show-review-label
              感想・レビュー
            .col-lg-9.review-show-text#review-show-text
              感想
          - if current_user.present? && user.id == current_user.id
            .row
              .col-lg-3
              .col-lg-3
                .show-review-btn#edit-review{ data: { dismiss: 'modal',
                toggle: 'modal' }, href: '#post-review-modal' }
                  %i.fas.fa-edit
                  編集
              .col-lg-3
                .show-review-btn#delete-read-book
                  %i.fas.fa-trash-alt
                  削除